### ISSUE TITLE
Problem Statement page adjustments [$30]

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#10]
![image](https://user-images.githubusercontent.com/3812270/48362791-7053cb00-e672-11e8-9941-4dcfa68cb801.png)

Please remove the "Players" heading above the problem statement title.

Can we also expand the leaderboard a bit more on this page?  Try making it about as wide as where the arrows point to.  This may be the main screen we show during the challenge, so it'll be better if the scores have more space.

**Comment by callmekatootie** [comment]
@jronak Interested in taking this one up?

**Comment by callmekatootie** [comment]
@jronak has agreed to work on this and submit PR asap. I have asked him to tag either @ajefts or @cwdcwd so that in case I am not around, you can review and merge the MR
