### ISSUE TITLE
Message page isn't showing message

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#11]
https://tco-leaderboard-ui-prod.herokuapp.com/page/message/4yq5xOiCGsoQCci68W2w2g

A recent change has made it so the message isn't displaying anymore.  I think it's related to https://github.com/topcoder-platform/leaderboard-ui/issues/4

Do we need to adjust the model?

**Comment by callmekatootie** [comment]
That is right - from the ticket #4 itself:

> Kindly note that you need to create a new attribute html in the content model. This will be a Long Text. In this, you can add your markdown content that will be translated to html when displaying on the UI.

**Comment by ajefts** [comment]
Got it.  Thanks.  I added the config.

**Comment by callmekatootie** [comment]
Some more info - you need to use markdown, which is converted to html by the app. So, you can control the styling - the app will only show it, not add any styles. WYSIWYG basically
