### ISSUE TITLE
Make showing scoreboard panel optional

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#12]
Since we aren't feeding live scores to all tracks yet, it would be useful to be able to hide the scoreboard panel so we can still use the other features of the pages.  

![image](https://user-images.githubusercontent.com/3812270/48450029-30700f00-e76a-11e8-8843-e48fde8977a0.png)

**Comment by callmekatootie** [comment]
I'll check what happens if this is hidden and get back - want to check if we need to make any adjustments or if it works right off the bat

**Comment by callmekatootie** [comment]
This has now been carried out. By default, leaderboard is not shown.

Set a property `showScoreboard` in the header component. This will be a boolean property - if Yes, leaderboard is shown else not shown
