### ISSUE TITLE
Ability to add pages and route to them

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#2]
On the content driven pages, in community-app we have a way to dynamically add pages to load under specific URL paths.  For example, if I create a page named foo I can then create a “route” for it in contentful that instructs the app to load the foo page when I hit topcoder.com/foo.  Think we could get that setup for this?  Or maybe ask Kiril to help with that part since he did it for community-app?

Here is an example of a "route" that we use for displaying a page via community-app:  https://app.contentful.com/spaces/b5f1djy59z3a/entries/1yqABWBQ44aUoGKYISCaOU

The use case is that we want to stage a lot of pages and have them ready to display.

Right now it looks like I’d have to keep replacing the page at /home for each track or every time we want to use that model

**Comment by ajefts** [comment]
@cwdcwd This one is actually pretty important.  We'll need to be able to do this in some way.  Let's check with Kiril to see if he can help...

**Comment by callmekatootie** [comment]
@ajefts Would this be like an index page that we have right now: http://tco-leaderboard-ui-dev.herokuapp.com/index

**Comment by ajefts** [comment]
More than an index page. I'd like to be able to create multiple "content" pages that leverage the various models.  However, if I do that right now then the app doesn't know how to display them (at least, that's my assumption).  Ideally, I'd like to be able to create content in contentful and automatically have the app know how to display it as a page.

**Comment by callmekatootie** [comment]
Let me know if I understand the requirements right:

You will create the content for each of the existing content models (we currently have 6). The content will not always be 6 ( or 1:1 for content models) but instead, you will have 1:n ratio for content models v/s content.

And then, you will visit the home page / landing page of the leaderboard ui, where you will see all the available content (a title and a description perhaps). You will click on a content link, which will then take you to another page, where you will see the data, just like you see now in the leaderboard ui

I intend to have
- 6 routes for the 6 tracks
- Within each route, we will have sub routes, where each sub route is a page of its own and are the pages that you see in the design

You will
- create content for each of the sub routes under each of the tracks
- launch the landing page, select the track and the sub route and that will be the final page you will see / page that will be displayed.

Let me know if I am wrong here

**Comment by ajefts** [comment]
Yes, I think you have got it.  I honestly don't even care if we have the index page.  The main thing is that I can create multiple instances of a content model and then navigate to it from the app.  So, basically something like 

http://ourapp.com/finalistsLB/<<contentId>>

That would give us the flexibility to create as many instance of a finalistsLB that we want and load them on demand.

**Comment by callmekatootie** [comment]
This one has been resolved.
