### ISSUE TITLE
Finalists page | Update the UI to display the finalists

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/leaderboard-ui#31]
OLD BEHAVIOUR

![image](https://user-images.githubusercontent.com/2317133/67919816-ea54cb00-fbc7-11e9-9b4e-4be6d6a1a22c.png)

NEW BEHAVIOUR

![image](https://user-images.githubusercontent.com/2317133/67919863-21c37780-fbc8-11e9-96f2-316c3d3ee6b2.png)

Designer's comment:

> For the finalists page, I added their faces in circles inside blob .The blobs shapes are in GDrive saved as vector files.

Note:
- The images of the finalists need to be extracted and provided. You can replace the old ones in `static/img/pic/finalist/<track_name>` - they will be uploaded to contentful
- This is only for the design track. Different tracks have different # of submitters. The arrangement of the rows is flexible currently, allowing us to provide 10, 12, 14, 16 submitters for any track - this needs to continue to work as before...

Another change:

![image](https://user-images.githubusercontent.com/2317133/67920017-a910eb00-fbc8-11e9-8b40-6497280ee10a.png)

- You have to update the text here (the font)
- You also have to update the background seen here.

**Comment by callmekatootie** [comment]
The sponsors is not in scope - we have different assets for them right now which we will replace later...

**Comment by srajas0** [comment]
Questions:

1. I have to export 14 images from the design and replace in `static/img/pic/finalist/UID`. Right?

2. In existing, a row has 8 images. In new design 7 images per row. Can you please more elaborate about ` allowing us to provide 10, 12, 14, 16 submitters`?

3. Each image is using different blobs shapes. Can I randomly show the blob shape for each image?

**Comment by callmekatootie** [comment]
PR merged - 1 minor issue remains: The FINALISTS text in Introducing Finalists does not have the same font weight as the design

**Comment by callmekatootie** [comment]
Fixed in https://github.com/topcoder-platform/leaderboard-ui/pull/50
