### ISSUE TITLE
More flexible message page [$50]

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#4]
Can we make the Message LB (https://app.contentful.com/spaces/b5f1djy59z3a/entries/4ST5FnkNkk2S4owEEcIOUY) a bit more flexible?  Right now, I can add a text message to the middle of the page, which is great.  However, can we make that middle section of the page an area that we can add any type of content to?  For example, we may want to put a video, images, images + text, etc.

We do this on other pages like https://app.contentful.com/spaces/b5f1djy59z3a/entries/3LR3dMd07CwA4QEGiAoiwq were we can generically add one or more content entries.

**Comment by callmekatootie** [comment]
@JRonak has taken this one up

**Comment by callmekatootie** [comment]
This has now been resolved.

Kindly note that you need to create a new attribute `html` in the content model. This will be a Long Text. In this, you can add your markdown content that will be translated to html when displaying on the UI.

If done correctly, it will show up as seen below:

![image](https://user-images.githubusercontent.com/2317133/48316153-cd656780-e605-11e8-9a39-29234263da9f.png)
