### ISSUE TITLE
Winners Page | Update page to match design

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/leaderboard-ui#42]
- for the images of the members, you need to extract the images and replace the ones under `static/img/pic/finalist/uid`. They will be uploaded to contentful from where they will be loaded
- We can have any number of finalists in a track. The current code was able to handle 10,12,14, 16 finalists at any time
- the same page - would display the winners after couple of seconds (instead of the prizes) - that should work too

**Comment by suppermancool** [comment]
@callmekatootie done in https://github.com/topcoder-platform/leaderboard-ui/pull/44
