### ISSUE TITLE
Finalists per countries

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/leaderboard-ui#45]
Design: https://marvelapp.com/d20201e/screen/62952670

This page does not exist. You need to create it.

We don't have any api for now that will give that data, so you can read off a json file perhaps.

Dynamic elements:

- the flag
- the tracks (only track name. `FINALISTS` text will be static and appended to each track name)
- the profile picture
- the member handle

**Comment by suppermancool** [comment]
@callmekatootie done in https://github.com/topcoder-platform/leaderboard-ui/pull/47 .
