### ISSUE TITLE
LeaderBoards

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/leaderboard-ui#46]
Designs: 

Algorithm leaderboard: https://marvelapp.com/d20201e/screen/62911345
F2F leaderboard: https://marvelapp.com/d20201e/screen/62911346

Leaderboards inside Problem Statement page and 1-on-1 page - https://marvelapp.com/d20201e/screen/62911343 and https://marvelapp.com/d20201e/screen/62911344

For now, we don't have any data. So you can read off a json file. For each member, we will basically have:
- the member handle, profile pic, country flag
- the scores

**Comment by callmekatootie** [comment]
@srajas0 assigned to you. For some reason I cannot find you in the Assignee list so mentioning manually

**Comment by srajas0** [comment]
@callmekatootie  In this issue, Do i need to create only right table in Problem Statement and 1-on-1 page right?
![image](https://user-images.githubusercontent.com/5876639/68076227-eac3b080-fdd7-11e9-90f9-0acbfbb932c2.png)

**Comment by callmekatootie** [comment]
yes correct

**Comment by callmekatootie** [comment]
@srajas0 

Sorry, noticed this text just now:

> No need to create leaderboard pages, right?

You DO need to create the leaderboard pages - the ones where only leaderboards are shown

Algorithm leaderboard: https://marvelapp.com/d20201e/screen/62911345
F2F leaderboard: https://marvelapp.com/d20201e/screen/62911346

**Comment by srajas0** [comment]
I need to create separate route (Leaderboard.JS) & i need to update table component based on track ( Algorithm & F2F).

**Comment by callmekatootie** [comment]
@srajas0 Yes, confirmed.

**Comment by callmekatootie** [comment]
Once the route is ready, you need to let me know the route path too - so that I can update that in contentful

**Comment by srajas0** [comment]
> Once the route is ready, you need to let me know the route path too - so that I can update that in contentful

Route Paths - 
http://localhost:3001/page/algorithm-leaderboard/entryId
http://localhost:3001/page/f2f-leaderboard/entryId
