### ISSUE TITLE
Primary sponsor image adjustment

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/leaderboard-ui#8]
We have a field for primary sponsor, which is good. However, it's making the image really big on some pages and impacting the layout. Here is an example:  

![image](https://user-images.githubusercontent.com/3812270/48290684-bc6bf900-e441-11e8-83e2-cebc7d9d6664.png)

Can we remove the primary sponsor display on all pages EXCEPT the sponsor page?  i.e.  Leave the logic on this page http://tco-leaderboard-ui-dev.herokuapp.com/page/sponsor/6DACtxIEgwyUMIQACKEIqM, but remove it from the other pages.  We'll just show the small icons so all sponsors will get the same treatment.

**Comment by callmekatootie** [comment]
@ajefts Could we not move that specific sponsor to the other sponsors list and keep the primary sponsor empty for the pages where needed?

**Comment by ajefts** [comment]
Yes, that’s what I’m suggesting.

**Comment by callmekatootie** [comment]
Sorry, I did not explain it clearly. What I mean is that can't we continue with the current arrangement, where we have a primary sponsor and secondary sponsors instead of removing the primary sponsor from the display altogether? You could leave it empty in contentful but we can keep it's container in the UI - in other words, we don't make any changes to the code. You only ensure that in contentful, primary sponsor is not used

**Comment by ajefts** [comment]
But then the main sponsor page doesn’t work?

**Comment by callmekatootie** [comment]
Main Sponsor Page: Use the primarySponsor attribute. Provide an image to it and the image will show up
All Other pages: Don't use the primarySponsor attribute. Leave it empty. Since there is no primary sponsor to be shown, the UI won't show it.

**Comment by callmekatootie** [comment]
This way, no code change would be needed

**Comment by ajefts** [comment]
ah, I think I see what you mean now.  Sorry for being slow on this one :)

**Comment by ajefts** [comment]
actually, 1 issue.  The app breaks if I remove the primary sponsor:

![image](https://user-images.githubusercontent.com/3812270/48363084-17386700-e673-11e8-84b3-e6a1fbe20725.png)


@callmekatootie

**Comment by ajefts** [comment]
@callmekatootie Need some help on this one if you're available

**Comment by callmekatootie** [comment]
huh... checking out why. will get back asap

**Comment by ajefts** [comment]
I think there is some general error handling missing them components of a page are left empty.  I've tried removing things various components from a page, but I always get that same 500 error.

**Comment by ajefts** [comment]
@callmekatootie I removed the primary.  Here is the page:  http://scoreboards.topcoder.com/page/finalists/3EvvMhMTEI8gygeIwsgmUy

**Comment by ajefts** [comment]
Actually, any page that uses the sponsor component errors now.  Try any of these....

http://scoreboards.topcoder.com/track/5Rm1zODfk4eCeaoEkkSSq2

**Comment by dushyantb** [comment]
@ajefts issue has been fixed, merged and deployed. Can you please verify and close the ticket?
